In [3]:
import pandas as pd

from supabase import create_client, Client

import requests

url: str = 'https://sgjnblasgncialxadixf.supabase.co'
key: str = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNnam5ibGFzZ25jaWFseGFkaXhmIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcwMzA5MzQyMCwiZXhwIjoyMDE4NjY5NDIwfQ.hAtZKiIo1GWefvk7dRS0X1UiB8_6KJ7trpuQ7zEssxc'


points = requests.get('http://localhost:8000/points_sorted?lat=0&long=0&token=driver_0').json()

df = pd.DataFrame(points)
df = df['points'].apply(pd.Series)
df[['id', 'name', 'lat', 'long']] = df.apply(lambda row: pd.Series({'id': row['id'], 'name': row['name'], 'lat': row['lat'], 'long': row['long']}), axis=1)

#coordinates = supabase.table('point').select('Longitude, Latitude').execute().get('data')
#names = df['Place Name'].values

In [4]:
df

id         name        lat       long   dist_meters
0   3    Supa Taco  40.806290 -73.945826  8.664313e+06
1   2   Supa Pizza  40.807475 -73.945810  8.664336e+06
2   1  Supa Burger  40.807416 -73.946823  8.664419e+06

In [5]:
coordinates = df[['long', 'lat']].values

In [6]:
coordinates

array([[-73.945826,  40.80629 ],
       [-73.94581 ,  40.807475],
       [-73.946823,  40.807416]])

In [7]:
import routingpy as rp
import numpy as np

api_key = '60cfa087-5e60-4bbc-83d0-c85d08810a93'	# get a free key at https://www.graphhopper.com/
api = rp.Graphhopper(api_key=api_key)
matrix = api.matrix(locations=coordinates, profile='car')
durations = np.matrix(matrix.durations)
print(durations)

[[  0  57 124]
 [172   0 124]
 [147  56   0]]


In [13]:
matrix

Matrix([[0, 57, 124], [172, 0, 124], [147, 56, 0]], [[0, 441, 587], [1188, 0, 647], [895, 400, 0]])

In [8]:
def symmetricize(m, high_int=None):
    
    # if high_int not provided, make it equal to 10 times the max value:
    if high_int is None:
        high_int = round(10*m.max())
        
    m_bar = m.copy()
    np.fill_diagonal(m_bar, 0)
    u = np.matrix(np.ones(m.shape) * high_int)
    np.fill_diagonal(u, 0)
    m_symm_top = np.concatenate((u, np.transpose(m_bar)), axis=1)
    m_symm_bottom = np.concatenate((m_bar, u), axis=1)
    m_symm = np.concatenate((m_symm_top, m_symm_bottom), axis=0)
    
    return m_symm.astype(int) # Concorde requires integer weights


In [9]:
sym_durations = symmetricize(durations)

In [10]:
sym_durations

matrix([[   0, 1720, 1720,    0,  172,  147],
        [1720,    0, 1720,   57,    0,   56],
        [1720, 1720,    0,  124,  124,    0],
        [   0,   57,  124,    0, 1720, 1720],
        [ 172,    0,  124, 1720,    0, 1720],
        [ 147,   56,    0, 1720, 1720,    0]])

In [17]:
# from concorde.problem import Problem
# from concorde.concorde import Concorde  


# def solve_concorde(matrix):
#     problem = Problem.from_matrix(matrix)
#     solver = Concorde()
#     print(solver)
#     solution = solver.solve(problem)
#     print(f'Optimal tour: {solution.tour}')
#     return solution

In [18]:
#solution = solve_concorde(sym_durations)

FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/artem/programming/auspak-backend/env/lib/python3.9/site-packages/concorde/concorde')

In [46]:
import numpy as np
from python_tsp.exact import solve_tsp_dynamic_programming


sym_durations
sym_durations[:, 0] = 0 #doesn't come back to the start
permutation, distance = solve_tsp_dynamic_programming(sym_durations)

In [52]:
permutation

[0, 3, 2, 5, 1, 4]

In [54]:
# pick alternate elements: these correspond to the originals
tour = permutation[::2]

# order the original coordinates and names
#coords_ordered = [coordinates[i].tolist() for i in tour]
#names_ordered = [df.loc[df['name'] == coordinates[i]['name'], 'name'].values[0] for i in tour]


In [55]:
tour

[0, 2, 1]